name: hello world
on: push
jobs: 
    my_first_job:
        runs-on: Ubuntu-latest
        steps: 
        - name:  welcome message
          run: echo "life is dicy"
        - name: make adirectory
          run: mkdir pracrtice
        - name: listing directory
          run:  ls
        - name: creating a file
          run:  touch info.txt
        - name: copying a file to a folder
          run: cp info.txt pracrtice
        - name: listing files in a folder
          run: ls

